app.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
import os

from routes import routes

app = Flask(__name__)
app.config.from_object(os.environ['APP_SETTINGS'])

app.register_blueprint(routes)

db = SQLAlchemy(app)

if __name__ == '__main__':
    app.run()

routes.py
from flask import Blueprint, render_template

routes = Blueprint('routes', __name__, template_folder='templates')

@routes.route('/')
def index():
    return render_template('index.html')

@routes.route('/about')
def about():
    return render_template('about.html')

@routes.route('/groups/')
def group_list():
    return render_template('group/list.html')

@routes.route('/groups/create')
def group_create():
    return render_template('group/create.html')

@routes.route('/groups/<int:group_id>/')
def group_detail(group_id):
    return render_template('group/detail.html')

@routes.route('/groups/<int:group_id>/join')
def group_join(group_id):
    return 'Oh, so you want to join group %d?' % group_id

@routes.route('/groups/<int:group_id>/leave')
def group_leave(group_id):
    return 'Oh, so you want to leave group %d?' % group_id

@routes.route('/prompts/')
def prompt_list():
    return render_template('prompt/list.html')

@routes.route('/prompts/<int:prompt_id>/')
def prompt_detail(prompt_id):
    return 'This is the page for prompt %d.' % prompt_id

@routes.route('/prompts/<int:prompt_id>/<int:response_id>')
def response_detail(prompt_id, response_id):
    return 'This is the page for response %d to prompt %d.' % (
        response_id,
        prompt_id
    )

templates/about.html
{% extends "layout.html" %}

{% block title %}
<title>About WriteNow</title>
{% endblock %}

{% block body %}
<article class="about">
    <header>
        <h1>About</h1>
    </header>
    <p>
        I like newsletters.
        I like that they&#8217;re emails.
        I like that they stay in my inbox.
        It gets me to actually read them.
        And there&#8217;s a personability, an informality, that is informed by its context.
        I feel like I&#8217;m being written <em>to</em>, rather than <em>for</em>.
        Newsletters, as a format, are rising in popularity, and justifiably so.
    </p>
    <p>
        These days we are writing more than ever.
        Between all the texts, tweets, and emails we send to one another, we&#8217;re writing enough to fill volumes.
        So I wanted to piggy-back on that behavior.
        I also wanted something that captured those positive feelings, but in the opposite direction.
        A newsletter is written by one person and sent to many people.
        What if we could have many writers send their writing all to the same place?
    </p>
    <p>
        I want us all to write about the same thing, to capture the range of voices that surrounds any one subject.
        I want that writing to come naturally.
        I want it to fit into the daily flow, to allow us to sneak some expression into an otherwise utilitarian routine.
        These likes and wants gave rise to this, WriteNow.
        It&#8217;s a way for writers to respond to prompts and then see all the results in one place.
    </p>
    <p>So that&#8217;s what this is and why it exists.</p>
    <p>&mdash; Allan</p>
</article>
{% endblock %}

templates/group/create.html
{% extends "layout.html" %}

{% block title %}
<title>Create a WriteNow Group</title>
{% endblock %}

{% block body %}
<form method="post" class="group create">
    <header>
        <h1>Create a Group</h1>
    </header>
    <label for="group-name">Name</label>
    <input type="text" id="group-name" />
    <label for="group-description">Description</label>
    <textarea id="group-description" placeholder="What is the focus of this group?"></textarea>
    <button type="submit">Create</button>
</form>
{% endblock %}

templates/group/detail.html
{% extends "layout.html" %}

{% block title %}
<title>Mock Group</title>
{% endblock %}

{% block body %}
<section class="group detail">
    <header>
        <h1>Mock Group</h1>
        <a class="sans" href="{{ url_for('routes.group_join', group_id=1) }}" title="Join this Group">Join this Group</a>
    </header>
</section>
{% endblock %}

templates/group/list.html
{% extends "layout.html" %}

{% block title %}
<title>WriteNow Groups</title>
{% endblock %}

{% block body %}
<section class="group list">
    <header>
        <h1>Groups</h1>
        <a class="sans" href="{{ url_for('routes.group_create') }}" title="Create a new Group">Create a new Group</a>
    </header>
    <ul>
        <li>
            <div class="group-links">
                <h2><a class="group-name sans" href="{{ url_for('routes.group_detail', group_id=1) }}">Mock Group</a></h2>
                <a class="group-join sans" href="{{ url_for('routes.group_join', group_id=1) }}">Join</a>
            </div>
            <p class="group-description">This is a mocked group. It is mocked until I get a database set up.</p>
        </li>
    </ul>
</section>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block body %}
<div class="cover">
    <svg width="350px" height="250px" viewBox="0 0 350 250">
        <title>WriteNow</title>
        <desc>The WriteNow icon is an envelope marked with an unread badge.</desc>
        <path d="M0,50 L300,50 L300,250 L0,250 L0,50 Z M21.7578125,70.6640625 L280.34375,70.5742188 L150,150 L21.7578125,70.6640625 Z M20,230 L20.0000001,90 L150,170 L279.585938,90 L279.585938,230 L20,230 Z" id="icon-envelope" fill-rule="evenodd"></path>
        <circle id="icon-badge" cx="290" cy="60" r="50"></circle>
    </svg>
    <h1>Write<a href="https://vine.co/v/eIXejbQ2utM">Now</a></h1>
    <p>It’s like newsletters, but backwards.</p>
    <p>Individually respond to writing prompts, then read everyone else's responses.</p>
    <form action="https://docs.google.com/forms/d/1fllwozw9ChsFKBfHP7VEmYIe7w-SSN7_dkGBAjhHb1M/formResponse" method="POST" id="ss-form" target="_self">
        <label for="entry_2118907566">What is your email address?</label>
        <input type="email" name="entry.2118907566" class="sans" id="entry_2118907566" value="" aria-label="What is your email address?  Please enter a valid email address." aria-required="true" required="" title="Please enter a valid email address." placeholder="enter your email">
        <input type="hidden" name="draftResponse" value="[,,&quot;3351150543781736871&quot;]">
        <input type="hidden" name="pageHistory" value="0">
        <input type="hidden" name="fvv" value="0">
        <input type="hidden" name="fbzx" value="3351150543781736871">
        <button type="submit" name="submit" value="Submit">Submit</button>
    </form>
</div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css')}}" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta description="It’s like newsletters, but backwards." />
    {% block title %}<title>WriteNow</title>{% endblock %}
    {% block author %}<meta author="Allan Lasser" />{% endblock %}
</head>
<body>
    <nav>
        <a href="{{ url_for('routes.index') }}" title="WriteNow homepage" class="logo">
            <svg width="28px" height="20px" viewBox="0 0 350 250">
                <title>WriteNow</title>
                <desc>The WriteNow icon is an envelope marked with an unread badge.</desc>
                <path d="M0,50 L300,50 L300,250 L0,250 L0,50 Z M21.7578125,70.6640625 L280.34375,70.5742188 L150,150 L21.7578125,70.6640625 Z M20,230 L20.0000001,90 L150,170 L279.585938,90 L279.585938,230 L20,230 Z" id="icon-envelope" fill-rule="evenodd"></path>
                <circle id="icon-badge" cx="290" cy="60" r="50"></circle>
            </svg>
            <span class="write">Write</span><span class="now">Now</span>
        </a>
        <ul class="sections">
            <li class="group section"><a class="sans" href="{{ url_for('routes.group_list') }}">Groups</a></li>
            <li class="prompt section"><a class="sans" href="{{ url_for('routes.prompt_list') }}">Prompts</a></li>
    </nav>
    {% block body %}{% endblock %}
    <footer>
        <ul>
            <li><a href="{{ url_for('routes.index') }}">Home</a></li>
            <li><a href="{{ url_for('routes.about') }}">About</a></li>
            <li><a href="mailto:Allan Lasser <lasser.allan+writenow@gmail.com>">Contact</a></li>
            <li><a href="https://github.com/allanlasser/writenow">GitHub</a></li>
        </ul>
    </footer>
</body>

templates/prompt/list.html
{% extends "layout.html" %}

{% block title %}
<title>WriteNow Prompts</title>
{% endblock %}

{% block body %}
<section class="prompt list">
    <header>
        <h1>Prompts</h1>
        <a class="sans" href="{{ url_for('routes.group_list') }}" title="Group list">Join a writing Group</a>
    </header>
    <ul>
        <li>
            <h2><a href="{{ url_for('routes.prompt_detail', prompt_id=1) }}">Mock Prompt</a></h2>
        </li>
        <li>
            <h2><a href="{{ url_for('routes.prompt_detail', prompt_id=2) }}">Mock Prompt</a></h2>
        </li>
        <li>
            <h2><a href="{{ url_for('routes.prompt_detail', prompt_id=3) }}">Mock Prompt</a></h2>
        </li>
    </ul>
</section>
{% endblock %}